### ISSUE TITLE
Sphere Renderer Geometry Mode Misses Shader File

### ISSUE THREAD

**Issue by geringsj** [UniStuttgart-VISUS/megamol#1104]
On a fresh master build, setting the test spheres example to geometry shader mode leads to the following error
```
(info)|[SphereRenderer] Using render mode 'Geometry_Shader'.
(error)|Unable to compile sphere shader: Error preprocessing shader:
ERROR: D:\megamol\out\install\x64-Debug\share\shaders\moldyn_gl\sphere_renderer\sphere_geometry.vert.glsl:10: '#include' : Could not process include directive for header name: moldyn_gl/sphere_renderer/inc/sphere_flags_vertex_getflag_geo.inc.glsl
ERROR: 1 compilation errors.  No code generated.

. [D:\megamol\plugins\moldyn_gl\src\rendering\SphereRenderer.cpp, megamol::moldyn_gl::rendering::SphereRenderer::createResources, line 670]
```

It seems the `D:\megamol\plugins\moldyn_gl\shaders\moldyn_gl\sphere_renderer\inc\sphere_flags_vertex_getflag_geometry.inc.glsl` shader file is not referenced correctly? Because there is no `_geo.inc.glsl` in the corresponding directory.

**Comment by sellendk** [comment]
Yes, sphere_flags_vertex_getflag_geometry.inc.glsl is the correct file that should be used. Renaming sphere_flags_vertex_getflag_geo.inc.glsl to sphere_flags_vertex_getflag_geometry.inc.glsl in the corresponding sphere_geomerty.vert file fixes the issue.
