### ISSUE TITLE
We need a prototype View3D_2

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#149]
- plus a CallRender3D_2 that 
  - exposes the matrices
  - has the new bounding boxes (chunk object-aligned, chunk axis-aligned, global dataset) all in world coordinates
  - has none of the weird-ass makescaledworld
- plus a new Renderer3DModule_2 that already implements daisychaining and does the boxes union and NOTHING ELSE - the camera is View3D_2's responsibility
- plus the Watermarkrenderer rewritten to be such a new module
- plus the compositor
- we need to use that as a test bed for replacing the camera
- a renderer needs to communicate isNewFrame on CallRender3D_2 if the incoming data has changed in any way and ONLY render in that case (or camera changes etc.). View3D should keep the previous result around (likely making render-to-FBO the default strategy for everything). This allows Hooks or Transmitters or Compositors to save time and bandwidth if the output is the same anyway.
- does this allow us to write all Views in a way that the GUI is refreshed all the time and the latest incoming FBOs are used to keep frame rates higher?
- we need a proper way for transporting the simulation time stamps to the view or anywhere else where it can be displayed. Currently, this requires a separate dataTime parameter and EVERY renderer in existence to move the current timestamp into the incoming CallRender. Also, since there is no class hierarchy for calls, this cannot be resolved generically.

**Comment by schatzkn** [comment]
Claim: Compositor could be useful as own Module

**Comment by gralkapk** [comment]
Will be tackled in PR #213

**Comment by schulzch** [comment]
Cleanup in #225 (Merge 2D/3D as much as possible) is related to this.

**Comment by schulzch** [comment]
Instead of a `Compositor`-Module, we possibly want to rework the `MuxRenderer` into a `StackView` and daisy-chain through `CallRenderView` which is 2D/3D-agnostic.

**Comment by tobiasrau** [comment]
Done with #213.
