### ISSUE TITLE
The OSPRay volume renderer still lives in the wrong coordinate system

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#165]
![image](https://user-images.githubusercontent.com/26002546/43401656-0648bbac-9411-11e8-9cdf-4a48ac725380.png)

same data, once as a volume with hopefully copied bounding boxes, once as raw particles.

**Comment by gralkapk** [comment]
This is fixed by gridOrigin and gridSpacing parameters derived from BBox.
