### ISSUE TITLE
CinematicCamera

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#210]
- KeyframeKeeper needs an explicit "load" button - because autoloading whenever you change the file name is not what you want if you put a lot of effort into placing keys
- it would be nice to be able to specify at least a prefix for the rendered images. appdir or wherever it is usually located could be read-only

**Comment by schulzch** [comment]
Actually, I guess you want a load/save button along with a "file has changed" state/flag that is set if the "in-memory-state" is not serialized to the specified file/filename. Correct?

That could be implemented using a "sync with file" boolean.

**Comment by reinago** [comment]
Sounds like a bit much, I was more worried of too much automation anyway. I'm also not sure such a file state detector is a fun thing to implement cross-platform.

**Comment by schulzch** [comment]
[simplefilewatcher](https://github.com/apetrone/simplefilewatcher) served me well in the past.

**Comment by braunms** [comment]
Both issues are fixed in current pull request.
