### ISSUE TITLE
Linker Error in InfoVis Plugin when switching between Release and Debug

### ISSUE THREAD

**Issue by schatzkn** [UniStuttgart-VISUS/megamol#212]
The linking of bhtsne.lib seems to be somewhat corrupted if you want to switch the compilation in Visual Studio between already existing Debug and Release builds. If you have the Release version of megamol installed and then try to install an already compiled Debug version, the following error occurs:

![image](https://user-images.githubusercontent.com/29492442/46680871-5134ca00-cbea-11e8-9ff5-8526ba546883.png)

Completely rebuilding the project in Debug mode fixes the issue, but takes an unnecessary amount of time. Switching the builds the other way around does not lead to the shown errors.

I tested everything under Windows 10 with Visual Studio 2017.

**Comment by schulzch** [comment]
Ganz seltsam. Das passiert nur bei der einen Lib?

**Comment by reinago** [comment]
is this actually gone for good?

**Comment by schulzch** [comment]
Think so, yeah. Closing until it re-appears.
