### ISSUE TITLE
OSPRay indirection over OpenGL

### ISSUE THREAD

**Issue by gralkapk** [UniStuttgart-VISUS/megamol#219]
OSPRay images get always blitted into OpenGL FBOs.
This requires a running X server on the respective machine, even on HPC nodes.
We need an OpenGL free render mode that has OSPRay render into main memory.
Something like a "render job".
This is required for true in situ capability.

**Comment by reinago** [comment]
is there no EGL on stampede? I think we discussed this, but I cannot remember.

**Comment by gralkapk** [comment]
EGL did not work on Stampede. However, whether Stampede does not support EGL or whether we have a bug, I can't tell.

**Comment by tobiasrau** [comment]
Directly connected to #381.
