### ISSUE TITLE
We need to get the locking straight

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#223]
- this is especially important when we use OSPRay, which continues rendering stuff in a separate thread until we change the scene graph, right?
- many other renderers do not properly unlock
- none of the newer datasources, especially transformers/generators, care about lockedness: we probably need an array of data that can needs to be checked and freed every time getdata comes around

**Comment by tobiasrau** [comment]
We have done various things #250 #283 #312. Is this still up to date?
