### ISSUE TITLE
Breaks on linux

### ISSUE THREAD

**Issue by fernanor** [UniStuttgart-VISUS/megamol#236]
/home1/05799/fernanor/software/megamol-dev/core/include/mmcore/CoreInstance.h:519:41: error: expected primary-expression before ‘>’ token
                         cb(*sl->CallAs<C>());
                                         ^
/home1/05799/fernanor/software/megamol-dev/core/include/mmcore/CoreInstance.h:519:43: error: expected primary-expression before ‘)’ token
                         cb(*sl->CallAs<C>());

**Comment by tobiasrau** [comment]
Fixed by fa3a7392a37f2547b738acc2a9349c405184c809
