### ISSUE TITLE
libpng causes issues in CI

### ISSUE THREAD

**Issue by tobiasrau** [UniStuttgart-VISUS/megamol#256]
All our CI tests fail with the same error:

    [ 32%] Performing download step (git clone) for 'libpng_ext'
    Cloning into 'libpng_ext'...
    fatal: unable to access 'https://git.code.sf.net/p/libpng/code/': gnutls_handshake() failed: Handshake failed
    Cloning into 'libpng_ext'...
    fatal: unable to access 'https://git.code.sf.net/p/libpng/code/': gnutls_handshake() failed: Handshake failed
    Cloning into 'libpng_ext'...
    fatal: unable to access 'https://git.code.sf.net/p/libpng/code/': gnutls_handshake() failed: Handshake failed
    -- Had to git clone more than once:
          3 times.
    CMake Error at /home/travis/build/UniStuttgart-VISUS/megamol-dev/build/core/libpng_ext-prefix/tmp/libpng_ext-gitclone.cmake:66 (message):
    Failed to clone repository: 'https://git.code.sf.net/p/libpng/code'

**Comment by schulzch** [comment]
Ist das noch aktuell?

**Comment by tobiasrau** [comment]
The LibPNG sources are hosted on sourceforge and from time to time the servers are not reachable. Our builds will fail during this down time. There is a clone by someone on Github, or should we create our own clone in the organization?
