### ISSUE TITLE
Powerwall MPI

### ISSUE THREAD

**Issue by FlorianFriess** [UniStuttgart-VISUS/megamol#285]
This is mainly a reminder for me (Florian) to look into the following error message. 

[0] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=0, new_comm=0x000000A6211DF788) failed
[ch3:sock] rank 0 unable to connect to rank 19 using business card <port=55198 description="10.35.1.20 KESHIKI20 " shm_host=KESHIKI20 shm_queue=6880:1256 >
unable to connect to 10.35.1.20 KESHIKI20  on port 55198, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[1] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=1, new_comm=0x0000008DC8CFF3D8) failed
[ch3:sock] rank 1 unable to connect to rank 0 using business card <port=55354 description="10.35.1.1 KESHIKI01 " shm_host=KESHIKI01 shm_queue=6864:1292 >
unable to connect to 10.35.1.1 KESHIKI01  on port 55354, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[2] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=2, new_comm=0x000000156FAFF118) failed
[ch3:sock] rank 2 unable to connect to rank 1 using business card <port=55383 description="10.35.1.2 KESHIKI02 " shm_host=KESHIKI02 shm_queue=6800:1244 >
unable to connect to 10.35.1.2 KESHIKI02  on port 55383, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[3] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=3, new_comm=0x000000C7A94FF3A8) failed
[ch3:sock] rank 3 unable to connect to rank 2 using business card <port=55200 description="10.35.1.3 KESHIKI03 " shm_host=KESHIKI03 shm_queue=3076:1248 >
unable to connect to 10.35.1.3 KESHIKI03  on port 55200, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[4] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=4, new_comm=0x000000C53AD0F688) failed
[ch3:sock] rank 4 unable to connect to rank 3 using business card <port=55168 description="10.35.1.4 KESHIKI04 " shm_host=KESHIKI04 shm_queue=1736:1244 >
unable to connect to 10.35.1.4 KESHIKI04  on port 55168, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[5] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=5, new_comm=0x000000F8B92FF6E8) failed
[ch3:sock] rank 5 unable to connect to rank 4 using business card <port=55372 description="10.35.1.5 KESHIKI05 " shm_host=KESHIKI05 shm_queue=2196:1256 >
unable to connect to 10.35.1.5 KESHIKI05  on port 55372, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[6] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=6, new_comm=0x000000ED057FF458) failed
[ch3:sock] rank 6 unable to connect to rank 5 using business card <port=57310 description="10.35.1.6 KESHIKI06 " shm_host=KESHIKI06 shm_queue=6168:1248 >
unable to connect to 10.35.1.6 KESHIKI06  on port 57310, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[7] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=7, new_comm=0x000000135E0FF2A8) failed
[ch3:sock] rank 7 unable to connect to rank 6 using business card <port=55097 description="10.35.1.7 KESHIKI07 " shm_host=KESHIKI07 shm_queue=5412:1248 >
unable to connect to 10.35.1.7 KESHIKI07  on port 55097, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[8] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=8, new_comm=0x0000008D1B8FF6B8) failed
[ch3:sock] rank 8 unable to connect to rank 7 using business card <port=54919 description="10.35.1.8 KESHIKI08 " shm_host=KESHIKI08 shm_queue=4236:1256 >
unable to connect to 10.35.1.8 KESHIKI08  on port 54919, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[9] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=9, new_comm=0x00000023396FF668) failed
[ch3:sock] rank 9 unable to connect to rank 8 using business card <port=55147 description="10.35.1.9 KESHIKI09 " shm_host=KESHIKI09 shm_queue=2248:1248 >
unable to connect to 10.35.1.9 KESHIKI09  on port 55147, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[10] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=10, new_comm=0x000000111E8FF268) failed
[ch3:sock] rank 10 unable to connect to rank 9 using business card <port=55120 description="10.35.1.10 KESHIKI10 " shm_host=KESHIKI10 shm_queue=4352:1248 >
unable to connect to 10.35.1.10 KESHIKI10  on port 55120, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[11] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=11, new_comm=0x00000034A3B8F2B8) failed
[ch3:sock] rank 11 unable to connect to rank 10 using business card <port=55126 description="10.35.1.11 KESHIKI11 " shm_host=KESHIKI11 shm_queue=6276:1248 >
unable to connect to 10.35.1.11 KESHIKI11  on port 55126, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[12] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=12, new_comm=0x0000000BDB2FF238) failed
[ch3:sock] rank 12 unable to connect to rank 11 using business card <port=55369 description="10.35.1.12 KESHIKI12 " shm_host=KESHIKI12 shm_queue=3636:1248 >
unable to connect to 10.35.1.12 KESHIKI12  on port 55369, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[13] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=13, new_comm=0x000000CC328FF588) failed
[ch3:sock] rank 13 unable to connect to rank 12 using business card <port=55228 description="10.35.1.13 KESHIKI13 " shm_host=KESHIKI13 shm_queue=5680:1252 >
unable to connect to 10.35.1.13 KESHIKI13  on port 55228, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[14] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=14, new_comm=0x000000946E8FF248) failed
[ch3:sock] rank 14 unable to connect to rank 13 using business card <port=55122 description="10.35.1.14 KESHIKI14 " shm_host=KESHIKI14 shm_queue=3292:1240 >
unable to connect to 10.35.1.14 KESHIKI14  on port 55122, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[15] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=15, new_comm=0x00000060F2FEF688) failed
[ch3:sock] rank 15 unable to connect to rank 14 using business card <port=57509 description="10.35.1.15 KESHIKI15 " shm_host=KESHIKI15 shm_queue=3668:1252 >
unable to connect to 10.35.1.15 KESHIKI15  on port 57509, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[16] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=16, new_comm=0x000000DAEF8FF098) failed
[ch3:sock] rank 16 unable to connect to rank 15 using business card <port=54958 description="10.35.1.16 KESHIKI16 " shm_host=KESHIKI16 shm_queue=1776:1248 >
unable to connect to 10.35.1.16 KESHIKI16  on port 54958, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[17] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=17, new_comm=0x000000219C6FF6A8) failed
[ch3:sock] rank 17 unable to connect to rank 16 using business card <port=55177 description="10.35.1.17 KESHIKI17 " shm_host=KESHIKI17 shm_queue=1320:1252 >
unable to connect to 10.35.1.17 KESHIKI17  on port 55177, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[18] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=18, new_comm=0x000000211A52F2D8) failed
[ch3:sock] rank 18 unable to connect to rank 17 using business card <port=54909 description="10.35.1.18 KESHIKI18 " shm_host=KESHIKI18 shm_queue=7092:1252 >
unable to connect to 10.35.1.18 KESHIKI18  on port 54909, no endpoint matches the netmask 10.37.0.0/255.255.0.0

[19] fatal error
Fatal error in MPI_Comm_split: Other MPI error, error stack:
MPI_Comm_split(MPI_COMM_WORLD, color=0, key=19, new_comm=0x00000066F833F668) failed
[ch3:sock] rank 19 unable to connect to rank 18 using business card <port=54909 description="10.35.1.19 KESHIKI19 " shm_host=KESHIKI19 shm_queue=5436:1240 >
unable to connect to 10.35.1.19 KESHIKI19  on port 54909, no endpoint matches the netmask 10.37.0.0/255.255.0.0

**Comment by FlorianFriess** [comment]
This was an MPI bug and had nothing to do with MegaMol -> closed

**Comment by braunms** [comment]
The MPI error was resolved by applying the pending updates on all three cluster headnodes.
We assume that due to the pending updates some stuff already has been applied in the background causing some stange network behaviour affecting MPI.
