### ISSUE TITLE
Leveling all the plugin names

### ISSUE THREAD

**Issue by schulzch** [UniStuttgart-VISUS/megamol#291]
We should refactor several plugin names to reduce confusion. This can be done painlessly by splitting the refactoring into 2 commits for conflict-freeness: 1. `git mv` 2. modify files). Proposed changes:

The mmstd-family:
- mmstd_datatools -> data_tools: remove stupid prefix (possibly, we want to split this into table_tools and particle_tools at some point?)
- mmstd_moldyn -> moldyn: remove stupid prefix
- mmstd_trisoup -> trisoup: remove stupid prefix
- mmstd_volume -> volume: remove stupid prefix

The outliers:
- adios_plugin -> adios_tools: be more specific, align with data_tools
- cinematiccamera -> cinematic: contains more than the camera
- imageviewer2 -> image: version one is long dead and align to <name> and <name>_calls
- OSPRay_plugin -> ospray_backend: be more specific

The toy plugins:
- template -> doc_template: indicate that this is a non-production plugin
- megamol101 -> doc_tutorial: indicate that this is a non-production plugin

Let's the bikeshedding begin :)

**Comment by schulzch** [comment]
Oh, I almost forget: maybe we want to find another name for "infovis", due to protein having "infovis" renderers. Possible names should relate to "high-dimensional geometry" and/or "multivariate data analysis".

**Comment by schulzch** [comment]
Partially done by #311

**Comment by moritz-h** [comment]
Done with #913
