### ISSUE TITLE
mmstd_datatools - FloatTableToParticles crashes

### ISSUE THREAD

**Issue by tobiasrau** [UniStuttgart-VISUS/megamol#30]
FloatTableToParticles crashes while the `colormode` is set to `Intensity` in the project file.
Setting the `colormode` to another value for starting and switching to `Intensity` while running, can be used as a workaround.

**Comment by moritz-h** [comment]
Archive issue data: [issue30.zip](https://github.com/UniStuttgart-VISUS/megamol/files/8709713/issue30.zip)
