### ISSUE TITLE
FlexEnum extension bug

### ISSUE THREAD

**Issue by tobiasrau** [UniStuttgart-VISUS/megamol#31]
Two identical modules with FlexEnums in the same MegaMol instance seem to share some data.
Changes to one of them goes to dev/null.

**Comment by reinago** [comment]
closed by 50d660d9b5e1df361ad9c46e853387981dbd249f

**Comment by moritz-h** [comment]
Archive issue data: [issue31.zip](https://github.com/UniStuttgart-VISUS/megamol/files/8709723/issue31.zip)
