### ISSUE TITLE
GUIView is not a complete implementation of AbstractView

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#333]
- example: crash when you try to make a screenshot of a GUIView: it does not implement OnRender.
TODO: find out what else is missing

**Comment by reinago** [comment]
- [x] onRenderView #367
- [x] isParamRelevant
- [x] DesiredWindowPosition
- [x] unpackMouseCoordinates

**Comment by braunms** [comment]
isParamRelevant() and DesiredWindowPosition() are already implemented in AbstractView.
unpackMouseCoordinates is now implemented in PR #383

**Comment by straubar** [comment]
@reinago Can you cherry-pick the commits from the astro branch? Or did Matthias already fix everything?

**Comment by braunms** [comment]
The changes concerning onRenderView we discussed should already have been merged in #366.
