### ISSUE TITLE
Unified Input Widget Behaviour

### ISSUE THREAD

**Issue by braunms** [UniStuttgart-VISUS/megamol#353]
Based on the comments during the last MegaMol meeting, I would like to suggest the following unified behaviour for most  input widgets of the GUI (int, float, string, color, vectors - not considered: bool, button, enum) :

- [ESC] Cancels the currently pending user input changes and no changes are applied to the parameter. (So ESC wouldn't be a hotkey for closing megamol any more) 
- [Enter] Confirms the currently pending user input changes and applies the changes to the parameter.
- [Tab] Same as [Enter]
- [Mouse Click (Ouside of widget -> Widget loses focus)]  Same as [Enter]

What do you think?
(Did I forget anyone to assign to this issue?)

**Comment by straubar** [comment]
I'm totally in favor for the first two entries, regarding [ESC] and [Enter].

The other two, for when the widget loses focus any other way, I do not have a strong opinion. I would be fine with either resetting the widget (like [ESC]) or applying the changes (like [Enter]), as long as the behavior for both [Tab] and [Mouse Click] are the same.

**Comment by reinago** [comment]
sounds good. I'm in favor of applying pending changes when the focus is switched.

**Comment by reinago** [comment]
We could even vote, right?

**Comment by reinago** [comment]
[ESC] = discard

**Comment by reinago** [comment]
[Enter] = confirm

**Comment by reinago** [comment]
Focus Lost = confirm

**Comment by straubar** [comment]
Focus Lost = discard

(for completeness sake)

**Comment by braunms** [comment]
Behaviours with most votes are implemented in #366
