### ISSUE TITLE
storecam does not have an effect

### ISSUE THREAD

**Issue by crowbar27** [UniStuttgart-VISUS/megamol#382]
When hitting the storecam button in the UI, `View3D::onStoreCamera` is called, which calls `this->cameraSettingsSlot.Param<param::StringParam>()->SetValue(str);` that acutally updates the parameter, but the change is not reflected in the UI, ie the `camsettings` field remains empty.

**Comment by braunms** [comment]
I'm already working on it an the fix will be realesed today ...

**Comment by braunms** [comment]
Fixed in PR #383
