### ISSUE TITLE
Crash when MegaMol is closed

### ISSUE THREAD

**Issue by FlorianFriess** [UniStuttgart-VISUS/megamol#39]
When we close the MegaMol that is running on the operator (minyou) it crashes, also see attached image. 
![megamol crash](https://user-images.githubusercontent.com/2973162/30266524-ee1455de-96df-11e7-9f2b-aea7b8d4a1f0.PNG)

We use the MegaMol (\vesta1\megamol20160815) for the powerwall.

**Comment by schatzkn** [comment]
Hopefully fixed by f312ef04e28985c99c953be4084ca4e3ecba4c06
