### ISSUE TITLE
Viewport vs. Viewport vs. Image_Tile

### ISSUE THREAD

**Issue by straubar** [UniStuttgart-VISUS/megamol#438]
What is the intended difference between a viewport and an image tile or is it the same thing with different names?

Depending on the answer to above question: what is "the MegaMol way" of getting the "correct" viewport information? Currently there exist at least three possibilities:
- extracting it from the fixed function pipeline \***bad**\*
- getting it from the render call, by asking for the viewport
- getting it from somewhere else (btw. where do we get this from?), by asking for the image tile

**Comment by schulzch** [comment]
Some "practical" definitions. Feel free to add them to the respective headers:
- A `View` is a render target (e.g. viewport + FBO or something similar)
- A (virtual) viewport is an affine transformation from NDC to window coordinates (OpenGL definition) - if you find something else calling itself a viewport with another definition please blame here :)
- Around tiles we have some synonymes: tile, image tile, rendering tile. Basically it is a rectangle in window coordinates that specifies which part of a (virtual) viewport should be rendered. The best way to play around with the concept should be the ScreenShooter.



> * extracting it from the fixed function pipeline ***bad***

100% agree.

> * getting it from the render call, by asking for the viewport

Yes.

> * getting it from somewhere else (btw. where do we get this from?), by asking for the image tile

No. Tiling and virtual viewports should be invisible to renderers as much as possible, i.e., the renderer should query for a viewport and camera matrix without knowing much about the PowerWall-ish and ScreenShoot-ish details.

Also note that the current implementation of virtual views and tiling is a crude hack: the base `View` should provide an interface for tiling and virtual viewports - there should be no need for this weird OverrideStuff construction, i.e., just set the fixed function viewport in some base class if the renderer implementation assumes fixed-function-style propagation.
