### ISSUE TITLE
#445 merge killed ADIOS2

### ISSUE THREAD

**Issue by tobiasrau** [UniStuttgart-VISUS/megamol#455]
The ADIOS implementation started to throw bad_allocation exceptions.
Reverting to a state before the build_speed PR #445 made ADIOS to work again.
Interestingly, using an external built ADIOS2 causes the same issues.

**Comment by straubar** [comment]
Does the problem occur while compiling or while running? And does it happen only for Debug/RelWithDebInfo?

**Comment by tobiasrau** [comment]
Found out that the wrong dll is installed.
