### ISSUE TITLE
Video overlays

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#472]
Make an overlay module for showing simulation time

- parameters: offset, multiplier, prefix (like 'frame'), suffix (like 'ns')
- slot to put the name of the parameter where the playback speed sits
- factors to distinguish current transport speed from playback speed (pause, play, forward, very fast forward, stacking arrows). like playback speed = 1 -> play, speed = 10 -> forward etc.
- parameters for size/position of time and icons

**Comment by braunms** [comment]
Will be resolved in PR #488
