### ISSUE TITLE
SetSlotUnavailable triggers Assert

### ISSUE THREAD

**Issue by invor** [UniStuttgart-VISUS/megamol#474]
Calling SetSlotUnavailable (always?) triggers an assert when checking whether the parent module of the slot matches the module it is about to be remove from:
`ASSERT(child->Parent().get() == this);`

This is most likely caused by modules not being fully created yet when slots are being added (i.e. made available) to modules in the constructor. Either this has to be fixed, or the assert needs to be replaced with a more appropriate safety check.

Maybe this issue will be automatically solved by the new graph?

**Comment by geringsj** [comment]
It seems the CoreInstance is currently not using SetSlotUnavailable() at all to manage the graph. 
The function gets called by the following modules only: CinematicView, ReplacementRenderer, SphereRenderer.

The new graph will likely not bother to support this functionality. We want to get rid of child/parent stuff in modules and calls ASAP.

I would be happy to look at a MegaMol project that triggers the mentioned ASSERT, as the other calls of the function seem to work just fine (?).

**Comment by straubar** [comment]
Having a quick look at the modules, I am certain the problem only occurs if calling SetSlotUnavailable() in the constructor. The modules, in which it works, call the function from within Render() or create().

I already used SetSlotUnavailable() in my private repository when I do not want the parent's slots to be available in my module. Doing so in the constructor triggers the assert, but apart from this seems to have no negative effect whatsoever when running in Release (without asserts enabled). This probably means that the "sanity" check can be removed. Can someone confirm this theory?
