### ISSUE TITLE
Installation / Documentation

### ISSUE THREAD

**Issue by HomesGH** [UniStuttgart-VISUS/megamol#475]
Trying to install MegaMol in Linux the following issues arose:

First of all, there are two different installation instructions (README and docs/MANUAL), which should be unified, e.g. adding the prerequisites to README. The configuration file in the MANUAL is not consistent with the one automatically generated during the installation process.

After installing (`cmake ..` , `make`, `make install`) I tried `./megamol.sh -i testspheres inst` , which does not work with neither the default config ( `1|Unable to instantiate call: target slot "::inst::rnd::rendering" not compatible with call "CallRender3D"` ) nor the suggested one in MANUAL (several errors).

**Comment by braunms** [comment]
Thank you for the hint concerning the doubled and outdated installation instructions.

The example projects are in a separate repository now. This repo is included in megamol per default in the directory `examples`. Please try `./megamol.sh -p ..\examples\testspheres.lua` to run the testsphere example.

**Comment by HomesGH** [comment]
Perfect, thank you! This was the solution of my Problem. You should definitely update the installation manual and the readme.md ;)
