### ISSUE TITLE
Installation and examples

### ISSUE THREAD

**Issue by HomesGH** [UniStuttgart-VISUS/megamol#522]
Hey,
I tried to install MegaMol on Linux. Even though it worked at the end (more or less), it was not very straight forward. You should unify your documentation (The one on the main page vs. _manual.md_ in _docs_), e.g. mention on the main page to  run `ccmake ../` instead, because solely running `cmake` does not work. Furthermore, it should be mentioned in _manual.md_ to run `make install `. For me, the package libglfw3(-dev) was an additional prerequisite not referred to in the doc.

At the end, I could start the testsphere example. Unfortunately, I wasn't able to use my mmpld-files. All examples including mmpld-files weren't working either....
Additionally, I couldn't find a way (or documentation; not even in the commits of the pull request on Github) to include the OverlayRenderer. It would be great, if you could provide an example.

Thanks a lot!
Best regards

**Comment by braunms** [comment]
Hey, thank you for your feedback. Here is an example project incorporating the OverlayRenderer (please rename file ending to 'lua' before using with MegaMol):
[testspheres_overlay.txt](https://github.com/UniStuttgart-VISUS/megamol/files/4225435/testspheres_overlay.txt)

**Comment by HomesGH** [comment]
ok, thanks. If figured out how it works for mmpld-files.
You have to add an A to dat**a** compared to my old config-files...
`mmCreateModule("MMPLDDataSource", "::testspheres::datA")`

**Comment by HomesGH** [comment]
Another issue:

I compared to my old version of MM, the SimpleSphereRenderer of the new one produces way darker images (see. the screenshot attached). Furthermore, the transport icon from the overlayRenderer always shows the "Pause" icon, even if the animation is started by pressing "Space". Maybe this is just some counter-intuitive "feature".

**Comment by HomesGH** [comment]
Here is a link to the picture:
https://tubcloud.tu-berlin.de/s/SpKtFoRBaLXGAfM

**Comment by braunms** [comment]
We fixed the lighting, thats why it is different to the old version. You can either change the position of the distant light or enable the switch **::testspheres::distantlight::EyeDirection**. The pause icon should disappear after the time given in the **::testspheres::overlay::transport_ctrl::duration** parameter. Change to 3.0, e.g. (Value 0 means that the transport icon is shown for ever, but I have to check this) You also have to tell the OverlayRenderer where to look for the time and the speed values. Try setting the parameter **::testspheres::overlay::transport_ctrl::speed_parameter_name** to  **::testspheres::view::anim::speed** and  **::testspheres::overlay::transport_ctrl::time_parameter_name** to **::testspheres::view::anim::time**. If you increase **::testspheres::view::anim::speed** you should see the fast and ultra fast forward icons ...

**Comment by HomesGH** [comment]
Thank you very much for the help! I made it work at the end :)
 But: **::testspheres::overlay::transport_ctrl::speed_parametr_name** missed an E, so its **parameter** instead of **parametr** and the second **speed_parametr_name** should be **time_parameter_name**. 
Yes, the icon disappears after 3 secs., so I changed the value to 0 (no disappearance) for testing. 

Is there a general documentation about all the plugins, e.g. the parameters and their options? So I don't have to ask for help on Github all the time ;)
As far as I know, the Configurator is only available for Windows, isn't it?

Best regards

**Comment by braunms** [comment]
I'm sorry for the typos. I fixed them in the post. Some plugins have a more or less extensive description of all provided modules and the available parameters. You have to check the Readme.md file of the plugins. If there is no readme for a plugin, I'm afraid that you have to keep asking :-P. Yes, the configurator is currently only available for Windows.

Best regards

**Comment by moritz-h** [comment]
This issue should be resolved, all discussed problems seems to be related to outdated things.
- The build system is more or less completely replaced meanwhile
- manual.md should be up to date and mention all required system dependencies
- MegaMol has now an integrated Configurator, supporting all platforms and the integrated configurator also has an interface for all parameters and slots.
