### ISSUE TITLE
New Configurator - SaveProject Unknown Error

### ISSUE THREAD

**Issue by invor** [UniStuttgart-VISUS/megamol#536]
When saving a project (in the new configurator) that contains a ParticlesToDensity module with a non-default sizex/y/z setting, an exception is thrown by vislib::UTF8Encoder::Encode(...); in line 841 in gui/src/configurator/GraphManager.cpp.

**Comment by braunms** [comment]
Thanks. Bug is fixed in commit 23a79a3.
