### ISSUE TITLE
Buffer unmap

### ISSUE THREAD

**Issue by gralkapk** [UniStuttgart-VISUS/megamol#557]
Unmapping a non-existing buffer is an invalid operation.
Should be no problem to remove the following line as buffer deletion should unmap automatically (see documentation)

https://github.com/UniStuttgart-VISUS/megamol/blob/33d80a5e20c168c19422b0b4973375da8c6db226/plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp#L396

**Comment by braunms** [comment]
The only intention was a proper cleanup :-P 
So it shouldn't be a problem to just remove the line.
Line is removed in commit bee60c8 of PR #555.
