### ISSUE TITLE
 Installation

### ISSUE THREAD

**Issue by HomesGH** [UniStuttgart-VISUS/megamol#689]
**Describe the bug**
I tried to install MM following the instructions in the manual (make build folder, `ccmake ../`, ** ), but it didnt work, because of the following error:
core/src/LuaAPI.cpp:21:10: fatal error: filesystem: Datei oder Verzeichnis nicht gefunden
 #include <filesystem>

It seems that a specific version of gcc or something is required. In the [manual](https://github.com/UniStuttgart-VISUS/megamol/blob/master/docs/manual.md), it says it was tested with `gcc 5.4.0`. All the prerequisites listed there are installed and up to date. My Linux-Distro in Ubuntu 18.04 with `gcc 7.5.0`.

Are there any specific C++ standards (e.g. c++-17) or gcc versions required and if so, do you know how I can set them?

Hope, you can help me and thanks in advance!
Best regards
Simon

** the installation instructions on the main page didnt work because `cmake` needs at least one argument ;) i think it should be `cmake ..` but this didnt work either but threw an error (require_external etc.)

PS: Please update your installation manual if not up-to-date ;)

**Comment by braunms** [comment]
Hello Simon, 
Thank you for pointing this out. We are sorry that the installation instructions are not up to date. This research software is constantly evolving and changes faster than we are able to maintain the manual. ;-) This is a detailed installation instruction for linux which will work with the current version:

$ mkdir megamol
$ git clone https://github.com/UniStuttgart-VISUS/megamol.git megamol/
$ cd megamol
$ mkdir build 
$ cd build
$ cmake ..

 > Proceed only if there are no more errors!

$ ccmake .

   > Configure using 'c' ('e' to exit configure menu) and then 'g' to generate and exit cmake

$ make && make install

$ cd install/bin
$ ./megamol.sh ../examples/testspheres_megamol.lua

An update of the manual will follow shortly. 
Please let us know if you face any further difficulties!

Best regards,
Matthias

**Comment by HomesGH** [comment]
Hi,

thank you very much for your immediate help! Unfortunately, as I pointed out before, `cmake ..` didn't work. I updated my distro to Ubuntu 20 and now it works. As I guessed, it seems to be a problem with the gcc version. Mine was 7 but at least 9 (or maybe 8?) is required. Here is my approach:

1. Make sure to meet the installation requirements; tested with:
```
$ cat /proc/version
Linux version 5.4.0-65-generic (buildd@lcy01-amd64-018) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021
```

2. Clone git repository:
`git clone https://github.com/UniStuttgart-VISUS/megamol.git`

3. Create build folder and change directory:
`cd megamol && mkdir build && cd build`

4. Prepare building process
`ccmake ..`

5. Configure with `c` and generate build files with `g`

6. Build MegaMol:
`make`

7. Go and get some coffee cause building takes some time...

8. Install MegaMol:
`make install`

9. Test it by running:
`cd install/bin && ./megamol.sh ../examples/testspheres_megamol.lua`


In the manual it says that the OSPRAY plugin is not installed by default. Do you know how I can install/enable and test it?

Best regards, 
Simon

**Comment by gralkapk** [comment]
Enabling BUILD_OSPRAY_PLUGIN_PLUGIN will allow the building of this plugin in MegaMol.
However, CMake will ask you to provide a path to an already installed OSPRay.
You can either get it from here https://www.ospray.org/ or fetch it from their Github repo.
If you build OSPRay yourself, make shure to enable the installation of externals in its CMake.
Otherwise MegaMol will complain about missing TBB and Embree.

**Comment by HomesGH** [comment]
Thanks for your help. Unfortunately it doesnt really work. I downloaded Ospray from the [webpage](https://www.ospray.org/downloads.html) as precompiled 64-bit package (`ospray-2.4.0.x86_64.linux.tar.gz`). After invoking `ccmake ..` , I enabled the BUILD_OSPRAY_PLUGIN_PLUGIN and set the Variable `ospray_DIR` to the folder in which the cmake files of Ospray are located (`/home/.../ospray-2.4.0.x86_64.linux/lib/cmake/ospray-2.4.0`). The build files could be generated but `make` leads to the following error:
```
[ 72%] Building CXX object plugins/OSPRay_plugin/CMakeFiles/OSPRay_plugin.dir/src/AbstractOSPRayRenderer.cpp.o
plugins/OSPRay_plugin/src/AbstractOSPRayRenderer.h:16:10: fatal error: ospray/ospray.h: Datei oder Verzeichnis nicht gefunden
   16 | #include "ospray/ospray.h"
```
Do you have any idea how to solve it?

**Comment by gralkapk** [comment]
I forgot to mention that OSPRay 2.x support will come with #681.
You have to use OSPRay 1.8.5 for now.

**Comment by HomesGH** [comment]
Ok, good to know! Now it works (at least the testspheres_megamol.lua without ospray). When I tried the ospray spheres, it doesnt work (of course not...)
`./megamol.sh ../examples/ospray/testspheres_ospray.lua`
`1|[GUI] GUIView module can only be used with mmconsole frontend.`

`./mmconsole.sh ../examples/ospray/testspheres_ospray.lua`
doesnt open any window...

Furthermore, the paths to the lua files must be absolute or relative to the megamol.sh file location. That means it is not possible to (create an alias to the megamol.sh file and) run the command in an arbitrary folder (eg. `../bin/megamol.sh testspheres_megamol.lua` in the examples folder).

**Comment by braunms** [comment]
Using the old frontend mmconsole, projects have to be loaded with the '-p' option:
`./mmconsole.sh -p ../examples/ospray/testspheres_ospray.lua`

**Comment by braunms** [comment]
Just a final thought on the first issue: The recently required full `std::filesystem` functionality is only available since gcc 8 with the -std=c++17 flag.

**Comment by braunms** [comment]
Some further explanation for clarity: There are currently two frontends available for megamol. The old `mmconsole` and the new one simply called `megamol`. So far, not every example has be adapted to the new frontend.

**Comment by braunms** [comment]
With this project file, you can use the ospray example with the new frontend: 
`./megamol.sh ../examples/ospray/testspheres_ospray.lua`:

----------------------

mmCreateView("Project_2", "View3D_2", "::Project_1::View3D_21")

mmCreateModule("OSPRayRenderer", "::Project_1::OSPRayRenderer1")
mmCreateModule("AmbientLight", "::Project_1::AmbientLight1")
mmCreateModule("OSPRaySphereGeometry", "::Project_1::OSPRaySphereGeometry1")
mmCreateModule("OSPRayOBJMaterial", "::Project_1::OSPRayOBJMaterial1")
mmCreateModule("TestSpheresDataSource", "::Project_1::TestSpheresDataSource1")

mmCreateCall("CallLight", "::Project_1::OSPRayRenderer1::lights", "::Project_1::AmbientLight1::deployLightSlot")
mmCreateCall("CallOSPRayStructure", "::Project_1::OSPRayRenderer1::getStructure", "::Project_1::OSPRaySphereGeometry1::deployStructureSlot")
mmCreateCall("CallRender3D_2", "::Project_1::View3D_21::rendering", "::Project_1::OSPRayRenderer1::rendering")
mmCreateCall("CallOSPRayMaterial", "::Project_1::OSPRaySphereGeometry1::getMaterialSlot", "::Project_1::OSPRayOBJMaterial1::deployMaterialSlot")
mmCreateCall("MultiParticleDataCall", "::Project_1::OSPRaySphereGeometry1::getdata", "::Project_1::TestSpheresDataSource1::getData")

**Comment by HomesGH** [comment]
Thank you very much for the explanations! I will try the given example soon. Can you also please give some short information /example on how I can use my own data in the above code?

**Comment by moritz-h** [comment]
> Furthermore, the paths to the lua files must be absolute or relative to the megamol.sh file location. That means it is not possible to (create an alias to the megamol.sh file and) run the command in an arbitrary folder (eg. `../bin/megamol.sh testspheres_megamol.lua` in the examples folder).

You are using the current master branch? (not older than 2 weeks)
Then there is no need to use the *.sh wrapper scripts. You can now just directly use the `megamol` and `mmconsole` binary. This should (TM) also work from any directory now.

(Two weeks ago we switched to build MegaMol with its plugins as single static linked binary. Previously the wrapper scripts where needed to set LD_LIBRARY_PATH to find all plugins and some dependencies. Your problem with the path was one on the list of features why we switched to static build. The cleanup process after this switch is not yet fully finished, therefore the .sh files are still there currently.)

**Comment by HomesGH** [comment]
Day 3/? of the installation process...

I'm using yesterdays master branch. Good to know, thank you for the info. I tried it, but of course there is an error (`error while loading shared libraries: libospray.so.0: cannot open shared object file: No such file or directory`). Probably some sym links must be generated by hand...
But at this point I don't really care, since it works with absolute paths as well (you can use the $PWD variable in linux) and I just want to make it work somehow...
Can you please provide two minimal working example on how to use my own data (mmpld generated with ls1) in the lua files with and without ospray. I tried to modify the lua testspheres_example but I couldn't find the right syntax.
Thank you!
Sorry, but it is really frustrating and error-prone to install Megamol without a proper documentation.

**Comment by braunms** [comment]
With the following minimal project you can load your own mmpld data set by replacing `$PATH_TO_MMPLD_DATA_SET_FILE$` (this project file is for the new frontend `megamol`):

mmCreateView("mmpld_test","View3D_2","::view") 

mmCreateModule("SphereRenderer","::renderer") 
mmCreateModule("DistantLight","::distantlight") 
mmCreateModule("BoundingBoxRenderer","::bbox") 
mmCreateModule("MMPLDDataSource","::data_source") 
mmCreateModule("TransferFunction","::transfer_function") 

mmCreateCall("MultiParticleDataCall","::renderer::getdata","::data_source::getdata")
mmCreateCall("CallGetTransferFunction","::renderer::gettransferfunction","::transfer_function::gettransferfunction")
mmCreateCall("CallLight","::renderer::lights","::distantlight::deployLightSlot")
mmCreateCall("CallRender3D_2","::bbox::chainRendering","::renderer::rendering")
mmCreateCall("CallRender3D_2","::view::rendering","::bbox::rendering")

mmSetParamValue("::data_source::filename",[=[$PATH_TO_MMPLD_DATA_SET_FILE$]=])

**Comment by braunms** [comment]
This is an analog example project using ospray:

mmCreateView("ospray", "View3D_2", "::ospray::view")

mmCreateModule("OSPRayRenderer", "::ospray::OSPRayRenderer1")
mmCreateModule("AmbientLight", "::ospray::AmbientLight1")
mmCreateModule("OSPRaySphereGeometry", "::ospray::OSPRaySphereGeometry1")
mmCreateModule("OSPRayOBJMaterial", "::ospray::OSPRayOBJMaterial1")
mmCreateModule("MMPLDDataSource", "::ospray::MMPLDDataSource1")
mmCreateModule("BoundingBoxRenderer", "::ospray::BoundingBoxRenderer1")

mmCreateCall("CallLight", "::ospray::OSPRayRenderer1::lights", "::ospray::AmbientLight1::deployLightSlot")
mmCreateCall("CallOSPRayStructure", "::ospray::OSPRayRenderer1::getStructure", "::ospray::OSPRaySphereGeometry1::deployStructureSlot")
mmCreateCall("CallOSPRayMaterial", "::ospray::OSPRaySphereGeometry1::getMaterialSlot", "::ospray::OSPRayOBJMaterial1::deployMaterialSlot")
mmCreateCall("MultiParticleDataCall", "::ospray::OSPRaySphereGeometry1::getdata", "::ospray::MMPLDDataSource1::getdata")
mmCreateCall("CallRender3D_2", "::ospray::BoundingBoxRenderer1::chainRendering", "::ospray::OSPRayRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::ospray::view::rendering", "::ospray::BoundingBoxRenderer1::rendering")

mmSetParamValue("::ospray::OSPRayRenderer1::useDBcomponent", [=[true]=])
mmSetParamValue("::ospray::MMPLDDataSource1::filename", [=[$PATH_TO_MMPLD_DATA_SET_FILE$]=])

**Comment by gralkapk** [comment]
OSPRay 2.x has made it into MegaMol yesterday.
Meaning, should you update MegaMol you would need to update OSPRay as well.

**Comment by HomesGH** [comment]
It works!!! Thank you so much :) It looks great with the ospray plugin :+1: 
I also made it running with multiple particle list (in the same mmpld file). Is it possible to show the particles in different colors? 
Current warning/error:

`100|[OSPRaySphereGeometry]: Color type not supported. Fallback to constant color.`

It works without ospray, but if ospray is enabled, they are all shown in green. Here is my lua file.

```
mmCreateView("ospray", "View3D_2", "::ospray::view")

mmSetParamValue("::ospray::view::backCol", "white")

mmCreateModule("OSPRayRenderer", "::ospray::OSPRayRenderer1")
mmCreateModule("AmbientLight", "::ospray::AmbientLight1")

mmSetParamValue("::ospray::OSPRayRenderer1::SamplesPerPixel",[=[1]=])
mmSetParamValue("::ospray::OSPRayRenderer1::numThreads",[=[14]=])

mmCreateModule("MMPLDDataSource", "::ospray::MMPLDDataSource1")
mmCreateModule("BoundingBoxRenderer", "::ospray::BoundingBoxRenderer1")
mmSetParamValue("::ospray::BoundingBoxRenderer1::boundingBoxColor", "#000000FF")
mmSetParamValue("::ospray::BoundingBoxRenderer1::enableBoundingBox", "True")

mmCreateCall("CallLight", "::ospray::OSPRayRenderer1::lights", "::ospray::AmbientLight1::deployLightSlot")

mmCreateModule("OSPRayOBJMaterial", "::ospray::OSPRayOBJMaterial1")
mmCreateModule("OSPRayOBJMaterial", "::ospray::OSPRayOBJMaterial2")
mmCreateModule("OSPRayOBJMaterial", "::ospray::OSPRayOBJMaterial3")
mmCreateModule("OSPRayOBJMaterial", "::ospray::OSPRayOBJMaterial4")

mmCreateModule("OSPRaySphereGeometry", "::ospray::OSPRaySphereGeometry1")
mmCreateModule("OSPRaySphereGeometry", "::ospray::OSPRaySphereGeometry2")
mmCreateModule("OSPRaySphereGeometry", "::ospray::OSPRaySphereGeometry3")
mmCreateModule("OSPRaySphereGeometry", "::ospray::OSPRaySphereGeometry4")

mmSetParamValue("::ospray::OSPRaySphereGeometry1::ParticleList",[=[0]=])
mmSetParamValue("::ospray::OSPRaySphereGeometry2::ParticleList",[=[1]=])
mmSetParamValue("::ospray::OSPRaySphereGeometry3::ParticleList",[=[2]=])
mmSetParamValue("::ospray::OSPRaySphereGeometry4::ParticleList",[=[3]=])

mmCreateCall("CallOSPRayStructure", "::ospray::OSPRayRenderer1::getStructure", "::ospray::OSPRaySphereGeometry1::deployStructureSlot")
mmCreateCall("CallOSPRayStructure", "::ospray::OSPRaySphereGeometry1::getStructureSlot", "::ospray::OSPRaySphereGeometry2::deployStructureSlot")
mmCreateCall("CallOSPRayStructure", "::ospray::OSPRaySphereGeometry2::getStructureSlot", "::ospray::OSPRaySphereGeometry3::deployStructureSlot")
mmCreateCall("CallOSPRayStructure", "::ospray::OSPRaySphereGeometry3::getStructureSlot", "::ospray::OSPRaySphereGeometry4::deployStructureSlot")

mmCreateCall("CallOSPRayMaterial", "::ospray::OSPRaySphereGeometry1::getMaterialSlot", "::ospray::OSPRayOBJMaterial1::deployMaterialSlot")
mmCreateCall("CallOSPRayMaterial", "::ospray::OSPRaySphereGeometry2::getMaterialSlot", "::ospray::OSPRayOBJMaterial2::deployMaterialSlot")
mmCreateCall("CallOSPRayMaterial", "::ospray::OSPRaySphereGeometry3::getMaterialSlot", "::ospray::OSPRayOBJMaterial3::deployMaterialSlot")
mmCreateCall("CallOSPRayMaterial", "::ospray::OSPRaySphereGeometry4::getMaterialSlot", "::ospray::OSPRayOBJMaterial4::deployMaterialSlot")

mmCreateCall("MultiParticleDataCall", "::ospray::OSPRaySphereGeometry1::getdata", "::ospray::MMPLDDataSource1::getdata")
mmCreateCall("MultiParticleDataCall", "::ospray::OSPRaySphereGeometry2::getdata", "::ospray::MMPLDDataSource1::getdata")
mmCreateCall("MultiParticleDataCall", "::ospray::OSPRaySphereGeometry3::getdata", "::ospray::MMPLDDataSource1::getdata")
mmCreateCall("MultiParticleDataCall", "::ospray::OSPRaySphereGeometry4::getdata", "::ospray::MMPLDDataSource1::getdata")

mmCreateCall("CallRender3D_2", "::ospray::BoundingBoxRenderer1::chainRendering", "::ospray::OSPRayRenderer1::rendering")
mmCreateCall("CallRender3D_2", "::ospray::view::rendering", "::ospray::BoundingBoxRenderer1::rendering")

mmSetParamValue("::ospray::OSPRayRenderer1::useDBcomponent", [=[true]=])
mmSetParamValue("::ospray::MMPLDDataSource1::filename", [=[pathToDatei/megamol_0001.mmpld]=])

```



PS: How is it possible to set the font size (in the lua file)? There is Windows -> Font Settings but it doesnt change anything when set to eg. 32.00.

PPS: Is it possible to change the mouse control? Its kind of messy with Ctrl+MouseLeft or Alt+MouseRight etc... Something like in Blender for example would be great ;)

**Comment by braunms** [comment]
I am glad to hear that it is working now! 

> PS: How is it possible to set the font size (in the lua file)? There is Windows -> Font Settings but it doesnt change anything when set to eg. 32.00.

In order to load a font in a different size, you also have to specify a `.ttf` font file. Two font files are already provided in the folder `..install\share\resources\fonts`. (A general GUI scaling for better support of high DPI displays is coming soon ...)

> PPS: Is it possible to change the mouse control? Its kind of messy with Ctrl+MouseLeft or Alt+MouseRight etc... Something like in Blender for example would be great ;)

In the configuration file `..install\bin\megamolcong.lua` you can change the option for the arcball behaviour to **on**: `mmSetConfigValue("arcball",     "on")

Since the text file based project configuration can be really exhausting, you can try to configure your projects more easy via the `configurator`. In the menu go to `Windows -> Configurator`. It is possible to start an "empty" MegaMol  (using the new frontend `megamol`) without providing a project file. You can add new modules on the fly.
Here you can find some additional information concerning the GUI: [gui](https://github.com/UniStuttgart-VISUS/megamol/blob/master/plugins/gui/README.md)

I have to pass your further questions concerning OSPRay to my colleagues ...

**Comment by HomesGH** [comment]
Thanks for the info! Its great to hear that higher DPI displays are supported soon. Can I somehow save the font + font size or apply it globally? Additionally, you should support copy+paste. Its quite a pain to type in long paths in the font name field ;)

Thank you, the arc ball option works!

It tried to add the screenshooter module in the configurator, but there is no way to connect it with the view module. Without connection there is an error when a screenshot is triggered.

```
1|Unable to find module "" for processing
1|Unable to find view or viewInstance "" for ScreenShot
```

It's the same when writing "::view" in the view field.

**Comment by moritz-h** [comment]
The screenshooter is not connected to the graph, it is a little bit strange to use. There is not direct connection to the graph.
Within the view field you must write the full namespaced instance name of the view, therefore please try `::ospray::view`.

Within the new megamol.exe we are trying to replace the old screenshoter. The basic screenshot functionality is already available, see the screenshot menu at top (press F2 to trigger). But at the moment this will basically just write the current framebuffer to disk, the old screenshooter module is more flexibel in kind of using different resolutions etc.

**Comment by braunms** [comment]
The font file and font size are stored in the GUI state within the project file and should be restored after loading the project again. The font loading will also be improved in the upcoming pull request #679.

I reproduced the behaviour that copy and paste is not working properly under linux. This is a bug and I will have a look on that.

Additional note to the screen shooting: If screenshots are taken consecutively, the given file name is prepended by an incrementing suffix. This way, no new file name has to be set after each screenshot.
