### ISSUE TITLE
View cube - rotation of a side view

### ISSUE THREAD

**Issue by pramathe** [UniStuttgart-VISUS/megamol#718]
The view cube is a nice possibility to set the camera to a side view of the cube. But I could not figure out how to rotate a side view within its plane.

For example: I want to see "Front", but rotated by 90°, 180° or 270° (within this plane)

**Comment by braunms** [comment]
So far, the view cube widget is just a first prototype. Further options like the one you mentioned will be added soon (maybe even this week).

**Comment by pramathe** [comment]
Awesome!  :)

**Comment by braunms** [comment]
Hi, an initial extension of the view cube which provides the selectable rotation of cube faces will be available with PR #723.

**Comment by braunms** [comment]
Please let me know, if you have any suggestions for improvement!

**Comment by pramathe** [comment]
Hi, thanks for the info! I'll give it a try as soon as PR #723 is merged.

**Comment by gralkapk** [comment]
#723 has been merged.

**Comment by braunms** [comment]
Added rotation arrows and picking of corners and edges with PR #770.
