### ISSUE TITLE
Ubuntu places libzmq somewhere else

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#75]
... again. or nowhere at all. investigate.

**Comment by Twinklebear** [comment]
I built with `CMAKE_INSTALL_PREFIX=<some path>` so that may have some effect. In the build directory it looks like libzmq was never copied to the install/lib dir, but was left in `./core/extlibzmq-prefix/src/extlibzmq-build/lib/`. Maybe the prefix was not used properly?

**Comment by tobiasrau** [comment]
The path to the lib directory was not correct in cmake.
