### ISSUE TITLE
Adios_plugin exception handling

### ISSUE THREAD

**Issue by sellendk** [UniStuttgart-VISUS/megamol#807]
Building the adios_plugin under Ubuntu (20.04.2 LTS) yields the following error:

no matching function for call to 'std::exception::exception(const char [42])'

thrown in line 475 CallADIOSData.h: throw std::exception("[CallADIOSData] Conversion not supported.");

It seems the std::exception constructor with the string argument is a MSVC extension and is not available on ubuntu.

**Comment by sellendk** [comment]
Also, ubuntu is not able to find std::transform without adding "#include <algorithm>" in CallADIOSData.h

**Comment by moritz-h** [comment]
Fixed in e95c68a9b983e92330609fe2ceb53c83f3313c7e
