### ISSUE TITLE
Windows installing problem

### ISSUE THREAD

**Issue by kevinwang1997** [UniStuttgart-VISUS/megamol#828]
**Describe the bug**
I tried to install MM following the instructions in the manual (5 Next, click Configure a few times (until all red entries disappear).), but it didnt work, because of the following error:

the installation instructions on the main page didnt work.  this didnt work either but threw an error (require_external etc.)

**Error**
CMake Error at externals/CMakeExternals.cmake:11 (include):
  include could not find requested file:

    C:/megamol/build/script-externals/cmake/External.cmake
Call Stack (most recent call first):
  CMakeLists.txt:47 (include)

CMake Error at externals/CMakeExternals.cmake:323 (add_external_project):
  Unknown CMake command "add_external_project".
Call Stack (most recent call first):
  frontend/services/CMakeLists.txt:12 (require_external)

**CMakeError.txt**
CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 pthread_create，函数 main 中引用了该符号 [C:\megamol\build\CMakeFiles\CMakeTmp\cmTC_ceba6.vcxproj]

C:\megamol\build\CMakeFiles\CMakeTmp\Debug\cmTC_ceba6.exe : fatal error LNK1120: 1 个无法解析的外部命令 [C:\megamol\build\CMakeFiles\CMakeTmp\cmTC_ceba6.vcxproj]

Hope, you can help me and thanks in advance!
Best regards
Kevin

**Comment by moritz-h** [comment]
> **Error**
> CMake Error at externals/CMakeExternals.cmake:11 (include):
> include could not find requested file:
> 
> ```
> C:/megamol/build/script-externals/cmake/External.cmake
> ```

That usually happens when the CMake configure is cancelled right after the start and the script-externals download did not finish yet. To fix it you need to clean the build directory and start a fresh configure.

For the second bug, please provide some more informations about your system, Windows Version, Compiler and Version, Generator, ...

**Comment by moritz-h** [comment]
Closing the issue, because no further feedback was provided. If there are still problems please feel free to comment and/or reopen the issue.
