### ISSUE TITLE
Sphere Shaders Conundrum

### ISSUE THREAD

**Issue by gralkapk** [UniStuttgart-VISUS/megamol#84]
These lines of code in the fragment shader of our Sphere Ray-Casting programs:
```
#extension GL_ARB_conservative_depth:require
layout (depth_greater) out float gl_FragDepth; // we think this is right
```
Actually, it may be wrong.
At least outside of MegaMol, they have not the desired effect on the depth test.

**Comment by reinago** [comment]
cross-check if this works with the new sphere-touch-plane thing
also, ALL sphere shaders (simple, simplegeo, ngsphere) need to use the same STP snippet. currently it is ridiculous.

**Comment by braunms** [comment]
Solution for the Conundrum:
    The default range of the OpenGL depth buffer is 0 (near) to 1 (far). The default value of glDepthFunc is GL_LESS.  This means only incoming framgents with a depth value less than the stored depth value (= fragments that are nearer) are passed to the fragment shader. With "#extension GL_ARB_conservative_depth : require" the early framgent test for depth is enabled for GLSL >= 4.0. "layout (depth_greater) out float gl_FragDepth" is only a promise(!) that the depth in the fragment shader will only be modified to larger values (fragments will only move further away). With this promise OpenGL applies the correct early fragment test to depth for the drawn point sprites. Nevertheless the fragment depth can be modified to any value in the fragment shader. Thus in my opinoion the current implementation is the right one and would also work 'outside' of megamol. (Performance increases noticeable with this settings.)

With PullRequest #248 all shaders will use same "Sphere Touch Plane" snippet which works for all render modes.
