### ISSUE TITLE
Overall TODOs

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#90]
- [ ] Matrices in CallRender3D
- [x] Powerwall-Lua-Test
- [x] Special instantiation templates to Lua projects
- [ ] Parameter files must be deprecated: replace by lua "projects" (they can be loaded on top of each other anyway). core should serialize these scripts instead
- [ ] Camera as a Module
- [ ] NGPF 0.1 serial
- [ ] VTK Data
- [x] Showcase / In Situ
- [ ] Core cleanup
- [ ] New test case for core
- [ ] Shader Factory based on snippets only
- [ ] Reworked Sphere Shader (less goo, deferred, ray setup in vertex shader)
- [ ] New HTML-based GUI
- [ ] OpenGL state (observer?)

**Comment by schulzch** [comment]
We should use projects/milestones for this kind of stuff or at the very least link to "doable task" issues. Close?
