### ISSUE TITLE
GenericParam min- and maxValue, customizable step size

### ISSUE THREAD

**Issue by sellendk** [UniStuttgart-VISUS/megamol#969]
## Min and max value
When a new ParamSlot is created with min- and maxVal set, e.g. 
```
check << new param::FloatParam(0.1f, 0.f, 2.f);
```
then the min- and maxVal gets reset by the constructor due to calling _initParam()_ and therefore the value is not bound.

https://github.com/UniStuttgart-VISUS/megamol/blob/d48fc4889f500528609053a5445202a9c0f6e5fb/core/include/mmcore/param/GenericParam.h#L38-L44

See PR #970 for a possible fix.

## Customizable step size
As also mentioned in Issue #539, it would be practical in some cases to a have a changeable step size. There is currently a PR (#970) where this has been tried to achieve, but since I am not too familiar with the complete underlying GUI structure of megamol, I would like to have an opinion whether I am going in the right directions for a possible implementation of a customizable step size and, if possible, some hints to what I need to watch out for and what additionally needs to be done. 

Especially for setting the step size during runtime and how it can be achieved only while being in the expert mode. I tried doing something equal to the value. I.e.

https://github.com/UniStuttgart-VISUS/megamol/blob/192a2ebe98cb0b0e4a4d44d2ac3e93b2390ff441/frontend/services/gui/src/graph/Parameter.cpp#L1829-L1830

and although you can set it technically, it doesn't save the step size permantly but instantly resets it.

**Comment by braunms** [comment]
Finished customizable step size in commit aaaf7d2 of PR #970.

**Comment by braunms** [comment]
Both issues are resolved with #970.
