### ISSUE TITLE
Issue with external dependency to oneTBB

### ISSUE THREAD

**Issue by Thinkpiet** [UniStuttgart-VISUS/megamol#984]
In the default configuration, megamol CMake build system tries to load https://github.com/oneapi-src/oneTBB.git with EXTERNAL_tbb_GIT_TAG = v2021.3.0 as defined in [externals/CMakeExternals.cmake](https://github.com/UniStuttgart-VISUS/megamol/blob/master/externals/CMakeExternals.cmake), line 840.

On my system (5.16.4-arch1-1), this causes the compilation process to fail with various issues, especially 
`Linking CXX shared library ../../gnu_11.2_cxx11_64_release/libtbbbind_2_4.so
/usr/bin/ld: error: /usr/lib: read: Ist ein Verzeichnis
collect2: Fehler: ld gab 1 als Ende-Status zurück`
and also
`_deps/tbb-src/src/tbb/tls.h:44:46: Fehler: »int pthread_setspecific(pthread_key_t, const void*)« erwartet 1 Byte in einer Region der Größe 0 [-Werror=stringop-overread]
   44 |     void set( T value ) { pthread_setspecific(my_key, (void*)value); }
      |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
Kompilierung wegen »-Wfatal-errors« beendet.`

If I update build/_deps/tbb-src to their master then I can compile everything without problems.

A colleague of mine has the same issue on a different machine with a different linux distribution (Ubuntu). 

I would suggest to update the external dependency so that megamol by default uses a newer version of oneTBB.

**Comment by reinago** [comment]
Hey Piet, thank you for the heads-up! Did you per chance check whether 2021.5.0 is good enough? It's always a bit risky to point at the moving head...

**Comment by moritz-h** [comment]
With vcpkg as new dependency system this should not be a problem anymore.
